### ISSUE TITLE
Can't verify and select a commit for a bot

### ISSUE THREAD

**Issue by svetdev** [anthive/io#58]
**Describe the bug**

**To Reproduce**
1. Go to https://profile.anthive.io/settings/'

**Expected behavior**
Can select commit and can play a game

**Screenshots**
<img width="1262" alt="screen shot 2019-01-25 at 9 11 41 am" src="https://user-images.githubusercontent.com/10056229/51763592-efb54000-20a0-11e9-869e-f5cffa3056fd.png">

**Comment by kezlya** [comment]
@svetdev thanks for filing a bug and welcome to AntHive.IO

The problem was in the path for your repo "https://github.com/https://github.com".

It has been fixed. 

You should be able verify and select commits now. Verification takes about 50 seconds. After that you can start a game.

Let me know if you encourage any other issues.

**Comment by svetdev** [comment]
Working. thanks!
